### PR TITLE
Fix flaky e2e failures with kindnet cni

### LINKED ISSUE #966: Flaky e2e failures with kindnet CNI
While transitioning to kindnet CNI in our KIND deployments, it was seen that HostNetworking e2e tests were occasionally failing. On debugging this issue, it was found that `kindnet` CNI does not create a dedicated CNI Interface on the nodes. Submariner relies on the CNI Interface to support some of the use-cases like Health-check between the GW nodes and HostNetwork to remote cluster support.

However, it was seen that as soon as we schedule a pod on the node, `kindnet` CNI creates a `veth-xxx` interface on the Host which can be used as a CNI Interface. So, in order to continue validating the above Submariner use-cases, we can schedule a dummypod as a DaemonSet in the clusters as a workaround (and this can be removed when we switch to a different CNI).

### PR DESCRIPTION
**Pull request by sridhargaddam**
While transitioning to kindnet CNI in our KIND deployments, it was seen that HostNetworking e2e tests were occasionally failing. On debugging this issue, it was found that kindnet CNI does not create a dedicated CNI Interface on the nodes. Submariner relies on the CNI Interface to support some of the use-cases like Health-check between the GW nodes and HostNetwork to remote cluster support. However, it was seen that as soon as we schedule a pod on the node, kindnet CNI creates a veth-xxx interface on the Host which can be used as a CNI Interface. So, in order to continue validating the above Submariner use-cases, this PR schedules a dummypod as a DaemonSet in the clusters as a workaround (and this can be removed when we switch to a different CNI).

Fixes: https://github.com/submariner-io/shipyard/issues/966
Related to: https://github.com/submariner-io/shipyard/issues/858
Signed-off-by: Sridhar Gaddam <sgaddam@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
```
In scripts/shared/deploy.sh line 74:
    run_subm_clusters deploy_daemonset ${KINDNET_WORKAROUND_NS} ${RESOURCES_DIR}/dummypod.yaml
                                                                ^--------------^ SC2086 (info): Double quote to prevent globbing and word splitting.
```
[Shell](https://github.com/submariner-io/shipyard/actions/runs/3182668168/jobs/5188913551#logs)

**Review by aswinsuryan — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

File: scripts/shared/deploy.sh [hunk 1]
```diff
@@ -67,6 +69,11 @@ function create_catalog_source() {
   echo "[INFO](${cluster}) Catalog source ${cs} created"
 }
 
+function schedule_dummy_pod_on_all_clusters() {
+    run_subm_clusters create_namespace ${KINDNET_WORKAROUND_NS}
+    run_subm_clusters deploy_daemonset ${KINDNET_WORKAROUND_NS} "${RESOURCES_DIR}"/dummypod.yaml
```
Comment (tpantelis) [inline scripts/shared/deploy.sh:74]: Should we delete the daemonset/namespace?

Comment (sridhargaddam) [reply scripts/shared/deploy.sh:74]: The daemonSet pod runs the command "sleep infinity". They will be deleted when the KIND clusters are deleted.

**Comment by dfarrell07** [comment]
Do we expect all the deploy jobs to still fail?

**Comment by sridhargaddam** [comment]
> Do we expect all the deploy jobs to still fail?

The deploy jobs are failing because shipyard is still running with weave CNI and its fully broken now :-( 
We need the following fix - https://github.com/submariner-io/shipyard/pull/956/files
But it needs rebase and since it does not have the fix from this PR it would fail too. So, let me include a small change to switch from weavenet to kindnet in this PR itself, so that we can validate the full functionality as part of this PR.

**Comment by tpantelis** [comment]
> The deploy jobs are failing because shipyard is still running with weave CNI and its fully broken now :-( We need the following fix - https://github.com/submariner-io/shipyard/pull/956/files But it needs rebase and since it does not have the fix from this PR it would fail too. So, let me include a small change to switch from weavenet to kindnet in this PR itself, so that we can validate the full functionality as part of this PR.

I think we should just combine the 2 PRs, ie include the commit from #956 here.

**Review by dfarrell07 — APPROVED** [review]
