### PR TITLE
Print clear error on invalid contex name

### LINKED ISSUE #1620: subctl verify fails silently if the context name is wrong
```
$ KUBECONFIG=~/AWS/awsocp1/auth/kubeconfig:~/AWS/awsocp2/auth/kubeconfig subctl verify --kubecontexts skitt-1 --kubecontexts skitt2
? You have specified disruptive verifications (gateway-failover). Are you sure you want to run them? No
Performing the following verifications: connectivity, service-discovery
Running Suite: Submariner E2E suite
===================================
Random Seed: 1634283097
Will run 37 of 41 specs
```

This is all the output; the exit code is 1.

Adding `--verbose` reveals what happened:

```
$ KUBECONFIG=~/AWS/awsocp1/auth/kubeconfig:~/AWS/awsocp2/auth/kubeconfig subctl verify --kubecontexts skitt-1 --kubecontexts skitt2 --verbose
? You have specified disruptive verifications (gateway-failover). Are you sure you want to run them? No
Performing the following verifications: connectivity, service-discovery
Running Suite: Submariner E2E suite
===================================
Random Seed: 1634283116
Will run 37 of 41 specs

STEP: Creating kubernetes clients
Oct 15 09:31:57.557: ERROR: Unable to load kubeconfig file /home/skitt/AWS/awsocp1/auth/kubeconfig:/home/skitt/AWS/awsocp2/auth/kubeconfig for context skitt2, this is a non-recoverable error
Oct 15 09:31:57.557: ERROR: loadConfig err: context "skitt2" does not exist
```

### PR DESCRIPTION
**Pull request by dfarrell07**
For the common error of pssing an invalid `--kubecontexts` flag to
`subctl verify`, we should clearly notify the user before exiting.

Closes: submariner-io/submariner-operator#1620

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

File: test/e2e/framework/framework.go [hunk 1]
```diff
@@ -331,6 +331,7 @@ func createRestConfig(kubeConfig, context string) *rest.Config {
 		Errorf("Unable to load kubeconfig file %s for context %s, this is a non-recoverable error",
 			TestContext.KubeConfig, context)
 		Errorf("loadConfig err: %s", err.Error())
+		By(fmt.Sprintf("Non-recoverable error: %s", err.Error()))
```
Comment (tpantelis) [inline test/e2e/framework/framework.go]: We already print the error and related info above via `Errorf`.  What does this add that isn't already covered? Also `By` is intended to document steps in a workflow.

Comment (dfarrell07) [reply test/e2e/framework/framework.go]: Thanks @tpantelis! The goal is to add output that shows without `--verbose`, as requested in https://github.com/submariner-io/submariner-operator/issues/1620.

**Comment by dfarrell07** [comment]
Can you re-review @tpantelis?

**Review by tpantelis — APPROVED** [review]

**Review by nyechiel — APPROVED** [review]
